### PR TITLE
Update Harmonie config and SVG

### PR DESCRIPTION
**Pull request by SailorSnoW**
Thanks for maintaining a dedicated faucet for the Substrate ecosystem.
As we are actually using an old faucet backend forked from the polkadot one, we would like to move to this faucet.

This PR is just some fix and adjustment for our testnet so we can start working with the application.

### CODE REVIEW

**Comment by ShankarWarang** [comment]
Thank you @SailorSnoW for the pull request. The changes are now live on the production.

**Comment by ShankarWarang** [comment]
@SailorSnoW May I know if the Harmonie testnet has a JSON RPC? We prefer it over websocket RPC for the frontier-based EVM chains/environments.

Suggestion: Please add your chain to the [ethereum-lists repo](https://github.com/ethereum-lists/chains), so it can be accessed from the chainlist.org

**Comment by ShankarWarang** [comment]
Look like the the testnet's JSON RPC and websocket RPC are same. Switched to JSON RPC. 
The faucet is ready to use now for the Harmonie testnet.

Please refill the faucet by sending the test tokens to this address: `0xFe50094e366802c9d0aa0b47fC19B275e92F0b7F`
@SailorSnoW

**Comment by SailorSnoW** [comment]
Our users are encountering this following error after we published the news on the discord: "Exceeded API limit for Harmonie Testnet".

Is that normal for the API rate-limit to be this strict ?

**Comment by ShankarWarang** [comment]
> Our users are encountering this following error after we published the news on the discord: "Exceeded API limit for Harmonie Testnet".
> 
> Is that normal for the API rate-limit to be this strict ?

Yes, there is a generic rate limiting. One can request only once in 24 hours for each address.
Do your users need to request more than once in a day for any specific application? If so, we can implement a custom rate limiting.

**Comment by SailorSnoW** [comment]
Haa thanks for the confirmation, wasn't sure it was a per-address rate limit.

No it's okay like this then, I think one request per day is just enough to limit it right.

**Comment by ShankarWarang** [comment]
> Haa thanks for the confirmation, wasn't sure it was a per-address rate limit.
> 
> No it's okay like this then, I think one request per day is just enough to limit it right.

Cool, thanks for the confirmation.

**Comment by ShankarWarang** [comment]
@SailorSnoW if you prefer redirecting your users to the Harmonie's dedicated page on the faucet, you can use this link:
[https://substratefaucet.xyz/allfeat-testnet](https://substratefaucet.xyz/allfeat-testnet)

**Comment by SailorSnoW** [comment]
Perfect thanks, was searching if a feature like that has been implemented, so cool :)

**Pull request merged**
